# Usa a imagem oficial do PHP com Apache na versão estável mais recente
FROM php:8.2-apache

# Copia todos os arquivos do seu diretório local para o diretório padrão do Apache no container
COPY . /var/www/html/

# Expõe a porta 80 para que possamos acessar o servidor web
EXPOSE 80